### ISSUE TITLE
Error handling when html.convert() is used

### ISSUE THREAD

**Issue by rysavyjan** [mathjax/mj3-demos-node#3]
I'm using code based on direct/tex2svg sample:

```
    //  Create DOM adaptor and register it for HTML documents
    const adaptor = liteAdaptor();
    RegisterHTMLHandler(adaptor);
    //  Create input and output jax and a document using them on the content from the HTML file
    const tex = new TeX({packages: options.packages.split(/\s*,\s*/)});
    const svg = new SVG({fontCache: (options.fontCache ? 'local' : 'none')});
    const html = MathJax.document('', {InputJax: tex, OutputJax: svg});

    //  Typeset the required TeX equation
    const node = html.convert(texEquation, {
        display: !options.inline,
        em: options.em,
        ex: options.ex,
        cwidth: options.width
    });
    // FIXME: how to get error message
    if (tex._parseOptions.error)
        return '';
    var svgOutput = adaptor.outerHTML(node);
    // FIXME: Isn't it possible to suppress mjx-container tag using some option?
    svgOutput = svgOutput.replace(/<(mjx-container|\/mjx-container).*?>/g, '');
    return svgOutput;
```

Unfortunately I didn't find out how to obtain errors (including error description) from html.convert() call. I would like to return meaningful message, like I see in speech/tex2svg sample. Is it possible when html.convert() is used?

**Comment by dpvc** [comment]
The error handling in `speech/tex2svg` is because that example is promise-based, and promises require that you have a `catch()` clause as they will fail badly if there is an error during the code that is run by the promise.  The errors that that code will catch are internal errors with MathJax, like if a file fails to load, not errors in the TeX code provided by the user, which will now throw an error (they simply produce a math expression that is the error message as would be displayed in the browser).

So assuming you want to trap the actual TeX errors (which none of the examples do), there are a number of ways to do that, which I describe below.

## Quick and Dirty

This is the easiest, but least elegant way to do it.  Here, we check for the error indicator and look up the error message (which is stored as an attribute of the `merror` element generated by the error).

```
    const node = html.convert(texEquation, {
        display: !options.inline,
        em: options.em,
        ex: options.ex,
        cwidth: options.width
    });
    if (tex.parseOptions.error) {
        const merror = tex.mathItem.root.childNodes[0].childNodes[0];
        console.log(merror.attributes.get('data-mjx-error'));
    } else {
       console.log(adaptor.innerHTML(node));
    }
```

Because we know the location of the `merror` element that the TeX input jax will produce, we can look into the MathML tree at the right location and grab the error message and return it (though I'm not sure how you are going to tell an error message from the SVG output, since you return strings in both cases).

## More Robust

It is a bit fragile to reply on the position of the `merror` element, so a better way would be to search the tree for it.  This can be done via the build-in tree walker.  Also, rather than simply return the error, we throw an error instead that can be trapped by an error-checking mechanism.  In this example, we use a TeX input jax post-filter to post-process the MathML before it is returned by `convert()`.

```
const tex = new TeX({packages: argv.packages.split(/\s*,\s*/)});
const svg = new SVG({fontCache: (argv.fontCache ? 'local' : 'none')});
const html = MathJax.document('', {InputJax: tex, OutputJax: svg});

tex.postFilters.add(({math, data}) => {
    if (!data.error) return;
    data.root.walkTree((node) => {
        if (node.isKind('merror')) {
            throw Error('TeX error: ' + node.attributes.get('data-mjx-error'));
        }
    });
});
```

Now we can use a `try-catch` command to detect and process the error:

```
try {
    const node = html.convert(texEquation, {
        display: !options.inline,
        em: options.em,
        ex: options.ex,
        cwidth: options.width
    });
    console.log(adaptor.innerHTML(node));
} catch (error) {
    console.log(error.message);
}
```

## Most Elegant

Perhaps the best way to handle the situation is to subclass the TeX input jax and override its `formatError()` function.  For example:

```
class MyTeX extends TeX {
    formatError(error) {
        throw Error('TeX error: ' + error.message);
    }
}

const tex = new MyTeX({options.packages.split(/\s*,\s*/)});
```

This will cause any TeX error to throw a javascript error, which you can trap using `try-catch` as above.  Alternatively, you could use promises, which I illustrate here:

```
MathJax.handleRetriesFor(() => {
    return html.convert(texEquation, {
        display: !options.inline,
        em: options.em,
        ex: options.ex,
        cwidth: options.width
    });
}).then(node => console.log(adaptor.innerHTML(node)))
  .catch(error => console.log(error.message));
```

The `catch` functions in both the  last two examples will trap both TeX errors and internal MathJax errors for processing.  Of course, you can use `try-catch` or promises in either one, depending on whether you need synchronous or asynchronous handling of the typesetting.

**Comment by dpvc** [comment]
> Isn't it possible to suppress `mjx-container` tag using some option?

Yes, use `adaptor.innerHTML()` rather than `adaptor.outerHTML()` so that only the contents of the container are serialized.  I have used this in my examples above.

**Comment by rysavyjan** [comment]
Davide, the "most elegant" MyTeX solution is EXACTLY what I was looking for, thank you. Works like a charm!

Thank you also for `adaptor.innerHTML()` hint.
