### ISSUE TITLE
mhchem throws error 

### ISSUE THREAD

**Issue by pkra** [mathjax/mj3-demos-node#4]
E.g., 

```
$ node direct/tex2chtml "x"

mj3-demos-node/node_modules/mathjax3/mathjax3/input/tex/mhchem/mhchem_parser.js:5
export var mhchemParser = {
^^^^^^

SyntaxError: Unexpected token export
    at Module._compile (internal/modules/cjs/loader.js:718:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (mj3-demos-node/node_modules/mathjax3/mathjax3/input/tex/mhchem/MhchemConfiguration.js:8:26)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)```
```

**Comment by pkra** [comment]
I realize this is an upstream issue in v3 but I've failed to figure out which branch of the v3 repo to look at.

**Comment by pkra** [comment]
Thanks.

**Comment by dagda1** [comment]
@dpvc this was fixed in #270 June 2019 but it still has not been released unless I am missing something

`export var mhchemParser = {`

The whole structure is so complicated.  The main branch is at 3.2.0 but if I do `npm info mathjax3 versions` I get

```
  '3.0.0-alpha.0',
  '3.0.0-alpha.1',
  '3.0.0-alpha.2',
  '3.0.0-alpha.3',
  '3.0.0-alpha.4',
  '3.0.0-alpha.5',
  '3.0.0-alpha.6',
  '3.0.0-beta.1',
  '3.0.0-beta.2',
  '3.0.0-beta.3',
  '3.0.0-beta.4'
  ```

If the fix has not been released which it has not, then how do we get it?  

Go to the repo and start looking at different branches until I track it down.

I think mathjax is great but the structure and versioning are verging on the insane.

**Comment by dagda1** [comment]
I am going to use [patch-package](https://www.npmjs.com/package/patch-package) but I would love to make this less crazy.

**Comment by pkra** [comment]
@dagda1 I'm not sure what problem you're running into. It does seem fixed for me -- if I clone this repo, run `npm i` and `$ node direct/tex2chtml "x"`, I get the expected output.

**Comment by dpvc** [comment]
I believe you are using the wrong package.  The `mathjax3` package was a temporary one while MathJax version 3 was being developed.  Once it went into production, the `mathjax` package went to version 3.  If you do `npm info mathjax version` you will get the current versions of MathJax.  If you look at the [documentation](https://docs.mathjax.org/en/latest/web/hosting.html#acquiring-the-mathjax-code) for MathJax, you will see that it suggests `mathjax@3` or `mathjax-full@3` (for the source distribution).  Note that the [npm page](https://www.npmjs.com/package/mathjax3) for the `mathjax3` page says it is a development package for v3, so that is not the official distribution.

**Comment by dpvc** [comment]
I've deprecated the `mathjax3` branch.

**Comment by dagda1** [comment]
@dpvc apologies, I had a moment earlier.  Thanks for the clarification, I wrote an [npm package](https://www.npmjs.com/package/@cutting/use-mathjax) that uses mathjax and I was seriously confused about which version to use.

I still do find it confusing but at least now it does not refer to a branch, should help.

**Comment by dpvc** [comment]
@dagda1, no problem, and glad you got it working.  Your sine demo is nice!
